### ISSUE TITLE
Special characters are being escaped by a backslash

### ISSUE THREAD

**Issue by infinitewhileloop** [wormi4ok/evernote2md#100]
Thanks a lot for creating this very useful tool. You helped me liberate my notes :smiley: 

I noticed however that a lot of special characters are being escaped by a backslash. I am using version 0.19.0.

E.g. for this short note in Evernote:
```
(parentheses) <angle> [square]
5 + 4 - 3
#hashtag bang! *star under_score
```

I receive this as output 
```
\(parentheses\) \<angle\> \[square\]

5 \+ 4 \- 3

\#hashtag bang\! \*star under\_score
```

I wrote a little script to solve this problem, maybe it could help someone else:
```bash
#!/usr/bin/env bash

shopt -s globstar

for file in notes/**/*.md; do
  printf '%s\n' "$file"
  sed -i -e 's/\\-/-/g' \
    -e 's/\\(/(/g' \
    -e 's/\\)/)/g' \
    -e 's/\\_/_/g' \
    -e 's/\\+/+/g' \
    -e 's/\\#/#/g' \
    -e 's/\\!/!/g' \
    -e 's/\\\*/*/g' \
    -e 's/\\</</g' \
    -e 's/\\>/>/g' "$file"
done
```

**Comment by wormi4ok** [comment]
Hi @infinitewhileloop ! Thanks for sharing your solution!
These special characters are escaped indeed, to ensure that the resulting Markdown can be rendered correctly. I gave an example in another issue https://github.com/wormi4ok/evernote2md/issues/55#issuecomment-907862189 .  

It really depends on what result is more valuable - raw files in Markdown format or rendered Markdown text. I guess it is a good candidate to become a cli flag in the newer version. 👍🏻

**Comment by wormi4ok** [comment]
Here you go - the new release [v0.21.0](https://github.com/wormi4ok/evernote2md/releases/tag/v0.21.0) does **not** escape special characters by default! 🎉
