### ISSUE TITLE
Crash with "killed" statement

### ISSUE THREAD

**Issue by wsargent** [wormi4ok/evernote2md#101]
**Problem statement**

The application is very slow and crashes around this line:

```
2023/07/07 22:35:06 [DEBUG] Saving file inbasket/Fwd-[Crypto-ops]_Recommendations_for_TLS_between_haproxy_and_nginx?.md
[1]    186716 killed     $HOME/bin/evernote2md --debug 'AAA - Inbasket.enex' inbasket
```

How do I build this?  I have IntelliJ IDEA and assuming I can add log statements I can track this down a bit.

The file's about 1.6 GB.

**Comment by wsargent** [comment]
I think the problem is that the size is such that it runs into an OS or program limit:

```go
	log.Printf("[DEBUG] Saving file %s/%s", path, title)
	if err := file.Save(path, title, bytes.NewReader(md.Content)); err != nil {
		return fmt.Errorf("save file %s: %w", path+"/"+title, err)
	}
```

**Comment by wormi4ok** [comment]
Hey @wsargent , you can definitely try to build the app yourself and narrow down the problem. To build it you will need to install [go](https://go.dev/) toolchain and run `go build` in the project root.

As a workaround, I would suggest trying one of the older version, [v0.18.2](https://github.com/wormi4ok/evernote2md/releases/tag/v0.18.2) for example. The decoding logic was changed in the latest release and there could be regressions in term of performance and memory management.
