### ISSUE TITLE
 The filename, directory name, or volume label syntax is incorrect.

### ISSUE THREAD

**Issue by martinandersen3d** [wormi4ok/evernote2md#15]
Windows 10 - Powershell:

PS C:\Users\Martin> cd "C:\Users\Martin\Desktop\New folder (3)"
PS C:\Users\Martin\Desktop\New folder (3)> .\evernote2md.exe --folders .\Evernote.enex
Notes: 31 / 2069 [=>_________________________________________________________________________] 1.50% 1s2020/10/22 03:19:13 [ERROR] save resource .\notes/Javascript_Abstract_Method_with_ES6-Yuri_Bett-Medium/image/1*SgjVeqiionF05LxxGN9TRA.jpeg: open .\notes\Javascript_Abstract_Method_with_ES6-Yuri_Bett-Medium\image\1*SgjVeqiionF05LxxGN9TRA.jpeg: The filename, directory name, or volume label syntax is incorrect.
PS C:\Users\Martin\Desktop\New folder (3)>

**Comment by martinandersen3d** [comment]
Nevermind. Thanks for a fantastic program!!! Just moved 1809 notes out of Evernote :D

**Comment by wormi4ok** [comment]
Thanks for the kind words and for reporting the issue. It's will be fixed in the next release! 👏
