### ISSUE TITLE
'illegal base64 data' bug

### ISSUE THREAD

**Issue by jgclark** [wormi4ok/evernote2md#17]
**Problem**: error message 'illegal base64 data at input byte X' when run on a Folder export .enex or a single file .enex.

**Example file**: here's the small single file .enex that the script fails at input byte 512. (To add it here I've had to rename it to .zip: just change back to .enex.
[Fritfetti - Say Yes to Sprinkles!.zip](https://github.com/wormi4ok/evernote2md/files/5541578/Fritfetti.-.Say.Yes.to.Sprinkles.zip)

Running v0.11.0 on latest release of macOS Catalina.

**Comment by wormi4ok** [comment]
Hey, @jgclark, thanks for reporting an issue. 
I checked and reproduced this bug on my machine. It seems that with the latest update, Evernote changed the export format a bit. I will need more time to examine the changes in the structure, update the app and publish a new release. Stay tuned :)

**Comment by wormi4ok** [comment]
Released a version with the fix - [v0.11.1](https://github.com/wormi4ok/evernote2md/releases/tag/v0.11.1), it looks not that big of a change in the structure, but I may have missed something. Please, let me know if you face more issues like this on your export.

**Comment by jgclark** [comment]
I've not done a very extensive test, but the first dozen or so tests have all seemed to work just fine.
Thank you for fixing so quickly.  I'm closing it, but obviously can be re-opened if anyone finds more subtle issues with the updated export format.
