### ISSUE TITLE
macOS security controls make it difficult to run

### ISSUE THREAD

**Issue by jgclark** [wormi4ok/evernote2md#18]
**Problem statement**. Apple's increasingly security makes it hard to run apps that aren't notarised from a verified developer.  This is affecting this utility.  It only seems to run for me from the downloads directory. When I move it to ~/bin or ~/Documents I get a warning message about it not being able to be verified, and then the process is killed.

Running latest release of macOS Catalina.

**Comment by wormi4ok** [comment]
Hey @jgclark , did you try to run `xattr -c evernote2md` as suggested on the [wiki page](https://github.com/wormi4ok/evernote2md/wiki/Run-the-binary-on-macOS-Catalina-or-higher)?

**Comment by jgclark** [comment]
Apologies, missed that there was an active wiki page. Very few repos seem to use them. But now I see a note about it at the bottom of the README.
