### ISSUE TITLE
Does Not Convert Nested Lists

### ISSUE THREAD

**Issue by hisaac** [wormi4ok/evernote2md#19]
First off, let me just say that I am amazed at how quickly and well this works! It converted all my documents in seconds.

**Problem statement**

That said, I did find one issue: It doesn't handle nested lists correctly.

**Example file**

Here is an example, a note that has some nested lists in it: 
[nested_list_example.zip](https://github.com/wormi4ok/evernote2md/files/5542805/nested_list_example.zip)

I would expect the lists to format like:

```markdown
* this is the first level
    * this is the second level
        * this is the third level
```

But instead it formats like

```markdown
* this is the first level

* this is the second level

* this is the third level
```

If I knew Go, I'd try to help with a solution myself, but I don't have any experience there.

**Comment by wormi4ok** [comment]
Hey @hisaac, thank you very much for the feedback.

This seems to be an issue in the underlying library. I'll try to figure this out tomorrow and will post the result here. 👍

**Comment by hisaac** [comment]
Thanks for the quick response @wormi4ok! Hopefully a fix is possible and simple. 😊

**Comment by wormi4ok** [comment]
Hi @hisaac, it turns out to be a simple fix indeed. Made a PR in the upstream library - https://github.com/mattn/godown/pull/3. 
Luckily, I use my own fork for some time, so you can already enjoy a new version [v0.12.0](https://github.com/wormi4ok/evernote2md/releases/tag/v0.12.0) that should format lists correctly. 🎉

**Comment by hisaac** [comment]
Hurray, thank you @wormi4ok!
