### ISSUE TITLE
Issue - Permission Denied

### ISSUE THREAD

**Issue by abhiank** [wormi4ok/evernote2md#2]
Hi, 
Thanks for making this. I was just trying it out for a note and on executing it, it simply said "Permission Denied". 

This is the command I wrote - 
```
/Users/abhimanyu/Desktop/evernote2md_0.3.0_MacOS_64-bit/evernote2md /Users/abhimanyu/Desktop/My\ Notes.enex /Users/abhimanyu/Desktop/My\ Notes 


-bash: /Users/abhimanyu/Desktop/evernote2md_0.3.0_MacOS_64-bit/evernote2md: Permission denied
```
How do I fix this? 
Thanks.

**Comment by wormi4ok** [comment]
Hello @abhiank ,

Thanks for sharing your experience! I think the problem might be in the binary file permissions. Could you please try to run:
```sh
chmod +x /Users/abhimanyu/Desktop/evernote2md_0.3.0_MacOS_64-bit/evernote2md
```
and then retry the command you mentioned.

Let me know if this helps, so I can fix the issue in the next release.

**Comment by abhiank** [comment]
Hey, thanks for the reply. 

Yup, this worked! Thanks!

Another piece of feedback - I had a note in Evernote with some code blocks. Those did not get  converted to code blocks in markdown.

**Comment by wormi4ok** [comment]
I uploaded a new release. It contains a single binary now and has correct permissions - https://github.com/wormi4ok/evernote2md/releases/tag/v0.3.1

Regarding the code blocks conversion, it would help a lot if you can upload an `.enex` file with an example note, that is not converted correctly. Or send it in an email to s@petrashov.ru. 

I didn't have any notes like this, but it seems to be an important use-case.

**Comment by abhiank** [comment]
Sure, I'll create a new issue for this and share a note with a code block..
