### ISSUE TITLE
Include mdate and cdate data in the conversion

### ISSUE THREAD

**Issue by hkievet** [wormi4ok/evernote2md#21]
It would be super useful to have a flag that would modify the saved files cdate and mdate to match the emex file's attributes.

**Comment by wormi4ok** [comment]
Hi, @hkievet 

This is a good idea, actually. It could even be the default behavior. I'll add it to my to-do list. 👍🏻

**Comment by hkievet** [comment]
@wormi4ok #23 

I'm not much of a golang developer (nor a github open source contributer), but I made a PR with some changes that seem to accomplish this enhancement.

**Comment by wormi4ok** [comment]
Hey @hkievet, I've released a new version [v0.13.0](https://github.com/wormi4ok/evernote2md/releases/tag/v0.13.0), that contains the changes you made! 🥇Check it out!

**Comment by hkievet** [comment]
@wormi4ok That's awesome thanks for the shoutout!
