### ISSUE TITLE
Won't run on MacOS Terminal - Solved

### ISSUE THREAD

**Issue by LeslieBarry** [wormi4ok/evernote2md#25]
Instead of evernote2md in terminal , replace evernote2md to ./evernote2md:

./evernote2md My\ Notes.enex TestEvernote

Source: https://forum.zettlr.com/discussion/153/import-from-evernote

**Comment by wormi4ok** [comment]
Hello @LeslieBarry,

Thanks for posting the solution here! This will be useful if you download a release manually to your Mac and have all files in the same folder. 
I'd highly recommend installing `evernote2md` via [Homebrew](https://brew.sh) on macOS. This way the app will be available anywhere ( so you can use `evernote2md` in any folder, without `./`) and it's easy to update/delete it.

```bash
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" # Install Homebrew 
brew install evernote2md # Install evernote2md 
brew upgrade evernote2md # Update
brew uninstall evernote2md # Delete it
```
