### ISSUE TITLE
batch convert enex files

### ISSUE THREAD

**Issue by tokeriis** [wormi4ok/evernote2md#26]
I want to export multiple folders as separate enex files from Evernote. I have a script that allows this. This leaves me with 50+ enex files.

Would it be possible to batch convert enex files, for instance by specifying a folder instead of an enex file?

**Comment by wormi4ok** [comment]
Hey, @tokeriis 

Thanks for mentioning this problem. For now, there is no such option in the tool, but with a tiny bash script you can achieve the result:

```bash
for file in *.enex; do
    [ -e "$file" ] || continue
    evernote2md "$file" ./notes
done
```

You can put all your enex files into one folder, `cd` in that folder, and paste this script into your terminal.

You can also save notes from each notebook in a separate folder if you slightly modify the script:

```bash
for file in *.enex; do
    [ -e "$file" ] || continue
    output=$(basename "$file" .enex)
    evernote2md "$file" "./notes/$output"
done
```

I'm still not sure how to incorporate this logic in the application and keep the interface clear as it is now. Hope this helps.

**Comment by tokeriis** [comment]
Thanks a lot!
