### ISSUE TITLE
Configurable tag export format

### ISSUE THREAD

**Issue by lzilioli** [wormi4ok/evernote2md#28]
**Context**
It looks like tags get exported surrounded by backticks.

I included a tag in the example I reported in https://github.com/wormi4ok/evernote2md/issues/27

The tag in the markdown is coming back as `Sample Tag`. I use some apps and markdown parsers that require one word tags, and that tags are preceded by a `#`. Is there anyway I could control the tag format of the exported markdown?

If I had to express it in javascript, my desired output would be:

```
function getTagText(tag: string): string {
  return `#${_.camelCase(tag)}`;
}
```

**Solution**
As far as how I could control or configure this via the command line, I do not have the best suggestion in mind.

**Comment by wormi4ok** [comment]
Hey, @lzilioli 

Thanks for the feedback! I already saw one fork of my project, with a similar change to what you describe. It looks like a valuable feature. 

I think it can be implemented as a string template option, like `--tagTemplate="#{{tag}}"` where default will be the same `` `{{tag}}` ``

**Comment by lzilioli** [comment]
Hi @wormi4ok thank you very much for working on this issue. I really appreciate it. Question about the open PR, how would I go about reformatting the `tag` text to camelCase before returning it?

**Comment by wormi4ok** [comment]
What is a use-case for camelCase specifically?

I wrote a short wiki page documenting the feature: https://github.com/wormi4ok/evernote2md/wiki/Custom-tag-template
The current implementation solves the word-splitting problem by replacing spaces with underscores so that you will get `#tag_form_evernote` for your example.
I'm really keen to avoid adding one more "tagTextTransformation" option to make this operation configurable.

**Comment by lzilioli** [comment]
@wormi4ok the app ia writer failes to recognize kebab case tags. They get totally omitted from the sidebar. Not sure about snake case. But I stick to camel because it's the most reliably parsed by all apps.

**Comment by wormi4ok** [comment]
Sorry, the issue got auto-closed. It still seems that camelcase is quite specific, and for most users, it may look strange. 
For now, the solution with underscores looks the most appropriate to me, but I can only suggest a few things. 
If you pay attention to tags, I believe it shouldn't be a big deal to reformat them in the Evernote app before converting to markdown. And if there are hundreds of tags, there is always an option to fork the project and implement the logic you need here: https://github.com/wormi4ok/evernote2md/blob/master/internal/tag.go#L28
