### ISSUE TITLE
Code blocks not parsed

### ISSUE THREAD

**Issue by abhiank** [wormi4ok/evernote2md#3]
Here's is an .enex file with some code blocks which on parsing with evernote2md do not contain the code blocks. 

https://anonymousfiles.io/RCg01WWC/
(Uploaded here for lack of support for .enex on github comments)

**Comment by wormi4ok** [comment]
The problem should be fixed in [version 0.4.0](https://github.com/wormi4ok/evernote2md/releases/tag/v0.4.0). Could you please try it on your note and write back here if the markdown looks as expected?

**Comment by abhiank** [comment]
Just tried it. Works perfectly! Thanks for the super quick fixes!
