### ISSUE TITLE
Tables are not valid Markdown tables

### ISSUE THREAD

**Issue by ar7hur** [wormi4ok/evernote2md#32]
A simple 2x2 Evernote table is exported as:

```
|a|b|
|c|d|
```

Which Github's markdown renders as:

|a|b|
|c|d|

I think it should be:

```
|a|b|
|--|--|
|c|d|
```

Which gives:

|a|b|
|--|--|
|c|d|

(Since tables are not official markdown, it may be a design decision. My view is based on Github's markdown.)

**Comment by wormi4ok** [comment]
That's true. Actually, the library I use supports table formating with proper markdown headers if the HTML input is semantically correct, using `<th>` HTML tags (table header). But Evernote formats all table cells using the `<td>` tag (table data), so it's harder to identify where the header is.

If you know any open source project that renders some input into markdown as you described - please share a link here, It would be curious to see how it's implemented.

I'll keep this issue opened for now.

**Comment by wormi4ok** [comment]
Just found out that the upstream library already implemented this! Version [0.17.0](https://github.com/wormi4ok/evernote2md/releases/tag/v0.17.0) uses an updated dependency and renders tables properly 🎉
