### ISSUE TITLE
Add bold text support

### ISSUE THREAD

**Issue by lkrych** [wormi4ok/evernote2md#34]
**Context**
<img width="914" alt="evernote" src="https://user-images.githubusercontent.com/14141810/104078054-0d6a0a00-51d1-11eb-8b2c-ae400d069c0c.png">

^ evernote

<img width="957" alt="evernote2md_now" src="https://user-images.githubusercontent.com/14141810/104078062-1529ae80-51d1-11eb-8e44-8d3fa52347a1.png">

^ markdown using evernote2md

**Solution**
https://github.com/wormi4ok/evernote2md/pull/33

**Comment by wormi4ok** [comment]
Fixed in version [0.14.0](https://github.com/wormi4ok/evernote2md/releases/tag/v0.14.0). Thanks again for the contribution! 🤝
