### ISSUE TITLE
Only EOF reported - no files produced 

### ISSUE THREAD

**Issue by sedlund** [wormi4ok/evernote2md#45]
**Problem statement**
Moved all my notes into Inbox and exported everything yesterday (2021-03-17) into Inbox.enex

`<en-export export-date="20210417T063918Z" application="Evernote" version="10.9.10">`

Inbox.enex is 257MB

Tried v0.15.0 on Windows and Linux

Output is:
```
./evernote2md -v Inbox.enex                                                                                  
2021/03/17 15:02:43 [DEBUG] Decoding a file: /home/user/Downloads/Inbox.enex
2021/03/17 15:02:49 EOF
```

No files are produced in notes.  Tried creating a ./notes and specifying - same result.

**Example file**

**Comment by wormi4ok** [comment]
Hey @sedlund,

Based on the output, it seems that `evernote2md` fails to decode the file - it doesn't even start converting.
I've just released a new version with additional debug logs - [v0.16.0](https://github.com/wormi4ok/evernote2md/releases/tag/v0.16.0). Could you please try to run again using this version with `-v` flag?
 
I hope that it will show which note exactly causes the parsing error. You can then export just this note and examine it or upload it here.

We need to narrow down the problem; going over 257MB is not an option :)

**Comment by sedlund** [comment]
Thanks that was helpful.

Inspecting the note that it stopped on showed that the content of the note was malformed in the export:

``` xml
    <content>
      <![CDATA[<?xml version="1.0" encoding="UTF-8" standalone="no"?>
      ]]>
    </content>
```

Content missing!

**Comment by wormi4ok** [comment]
This is much better. I've written a test case for this kind of input and will try to find an elegant solution. Thank you 🙌🏻
