### ISSUE TITLE
Checkbox missed when mixed with ordered list

### ISSUE THREAD

**Issue by xshuai1006** [wormi4ok/evernote2md#62]
**Context**
In my evernote, many notes have ordered list with order number followed by checkbox: 
![剪贴板01](https://user-images.githubusercontent.com/1651111/132368253-553a405e-fd5e-454d-8949-0cfd8d2a141f.jpg)

and after converted with evernote2md, ordered list remains, while checkbox missed.
![剪贴板02](https://user-images.githubusercontent.com/1651111/132368526-d926237d-15c6-4615-8b77-07e6ce685a23.jpg)

I use evernote2md because I want to transfer my notes from 印象笔记 (evernote in china) to Obsidian, and I find that Obsidian support ordered list with checkbox followed, I really like this feature:
![QQ截图20210907231247](https://user-images.githubusercontent.com/1651111/132369055-7b05d081-ca8d-4551-91cf-152c472fa753.jpg)

**Solution**
So I hope evernote2md can support keep checkbox when it followed with ordered list. I know that ordered list with checkbox is not normal markdown syntax, and maybe not be supported by most markdown editor, so I think maybe this feature can be addea as a command option.

**Comment by wormi4ok** [comment]
Hello @xshuai1006 , thanks for reporting the problem. The solution you propose here contributes well to the discussion in #50. I'll try to make checkboxes conversion work as expected 👍🏻

**Comment by combin** [comment]
This feature is very important for me too, looking forward to it very much.

**Comment by wormi4ok** [comment]
Yeah, thanks for posting it here! I will pick it up right after I finish with https://github.com/wormi4ok/evernote2md/issues/58

**Comment by wormi4ok** [comment]
The new release - [v0.18.0](https://github.com/wormi4ok/evernote2md/releases/tag/v0.18.0) adds correct handling for todo lists with checkboxes! 🥳
