### ISSUE TITLE
is it possible to add custom header for all output markdown files

### ISSUE THREAD

**Issue by czyt** [wormi4ok/evernote2md#64]
**Context**
is it possible to add custom header for all output markdown files.in this case we can export all evernotes to
markdown files which can be hosted on the hugo and other static blog platform.

**Solution**
what the feat we wannt is something like below:
- buildin info canbe embed `tag` `title` `author` `createTime` 
- additional dynamic or fixed props

**Comment by stolbovd** [comment]
Flag `--addFrontMatter` reates one markdown file per note for [Jekyll](https://jekyllrb.com/docs/front-matter/)

```
evernote2md --addFrontMatter input.enex output
```
