### ISSUE TITLE
After exporting images to markdown, the order of images is confused

### ISSUE THREAD

**Issue by UzJu** [wormi4ok/evernote2md#65]
After exporting images to markdown, the order of images is confused

**Comment by wormi4ok** [comment]
Hey @UzJu , could you please explain what do you mean by "confused"? Is the order is bot correct? Could you share an example enex file?

**Comment by UzJu** [comment]
I'm very sorry, brother, this problem is a bug of typora in Macos, such as using evernote to export .enex format files, and then use your tool evernote2md to convert to .md markdown files, after using typora batch upload, images, it will cause the order of the images
