### ISSUE TITLE
Spaces in titles converted to empty titles

### ISSUE THREAD

**Issue by Karut** [wormi4ok/evernote2md#83]
**Problem statement**

Basically the title. Some notes with spaces in their titles are being named _unnamed note_. I could not find a pattern yet which differentiates between notes that get this treatment and those who dont. Will update the pots with an example.

**Example file**

**Comment by wormi4ok** [comment]
Hi @Karut ! There is no logic in the conversation that would use "unnamed" as a fall back value for title. But it would be curious to see an example. It may be some unexpected side effect in the Evernote export format and if the .enex file contains the expected title somewhere - it should be possible to build a workaround.

**Comment by Karut** [comment]
Hi! 

Here is example .enex file where both notes get to be "unnamed". Attached the converted notes as well. Thanks for the help! 

[Archiv.zip](https://github.com/wormi4ok/evernote2md/files/9882135/Archiv.zip)

(On other note, perhaps I will add another issue: all my notes get a markdown heading named after their title. I am pretty sure this is not intended behaviour?, see example from on of the notes in the enex file)

![image](https://user-images.githubusercontent.com/16340610/198367602-7dfe26e2-63a6-494c-95a9-8bed14da9439.png)

**Comment by wormi4ok** [comment]
I've looked at the raw `.enex` export in the archive you've shared and I believe the conversion worked as expected. Both notes have `Unbenannte Notiz` as a value for the note title.

<img width="715" alt="image" src="https://user-images.githubusercontent.com/282550/201525124-4c87be58-cf3c-4a35-876f-d6c94c1674de.png">

And regarding this:

> (On other note, perhaps I will add another issue: all my notes get a markdown heading named after their title. I am pretty sure this is not intended behaviour?, see example from on of the notes in the enex file)
> 

This is an intended behaviour. Filesystems have many limitations and often do not allow to specify the filename exactly like it is written in the note title. But we can preserve the original title by prepending it in the beginning of the file content.

**Comment by Karut** [comment]
> I've looked at the raw .enex export in the archive you've shared and I believe the conversion worked as expected. Both notes have Unbenannte Notiz as a value for the note title.

I figured out that the titles are exported from Evernote as expected with the Evernote legacy version. So it's a big on Evernotes part. 

> (On other note, perhaps I will add another issue: all my notes get a markdown heading named after their title. I am pretty sure this is not intended behaviour?, see example from on of the notes in the enex file)

> This is an intended behaviour. Filesystems have many limitations and often do not allow to specify the filename exactly like it is written in the note title. But we can preserve the original title by prepending it in the beginning of the file content.

Is there an option to turn this off? My files are correctly imported in Obsidian with their specified titles. This would save me the hassle of deleting the headings of thousands of my notes.

**Comment by wormi4ok** [comment]
Yeah, since this is specific to the tool you use for managing markdown notes, I'd try to avoid additional flags for conversion. But the beauty of open source is that you can compile your own build with [this line](https://github.com/wormi4ok/evernote2md/blob/master/internal/convert.go#L82) commented out.

Or, on a UNIX-based operating system, a combination of [find](https://stackoverflow.com/questions/10445934/change-multiple-files) and [sed](https://unix.stackexchange.com/questions/256494/what-does-sed-i-1d-do) would do the trick for you.

Good luck, and thanks for bringing it up!
