### ISSUE TITLE
Inline code in list item not working

### ISSUE THREAD

**Issue by aneeshvartakavi** [wormi4ok/evernote2md#92]
Hello!

Thanks for the tool! I'm using version 0.18.0, and I noticed that inline code within a list is not exported correctly.

Example Note:

> This is a test to see if `inline code` will be correctly exported.
> 
> - Checking if `code` in a list works.
> 
> ```
> What about entire code blocks?
> ```
> 

After conversion:

> This is a test to see if `inline code` will be correctly exported.
> 
> - Checking if                                                                                     <--- Incorrectly truncated
> 
> ```
> What about entire code blocks?                                                  
> ```
> 

Any suggestions or workarounds?

**Comment by wormi4ok** [comment]
Hi @aneeshvartakavi ! The issue related to styled items in the lists was fixed in [v0.18.1](https://github.com/wormi4ok/evernote2md/releases/tag/v0.18.1)  patch release. Please, give it a try and let me know if worked for you! 🙌🏻

**Comment by aneeshvartakavi** [comment]
Thanks so much, 0.18.1 seems to fix it!
