### ISSUE TITLE
files and images not exporting correctly

### ISSUE THREAD

**Issue by michaelsmhc** [wormi4ok/evernote2md#97]
Hello,
I used this tool to convert a ~4000 note notebook and it did so very quickly. However the pdfs only show random text (e.g 3-4 pages of JVBERi0xLjUNCjQgMCBvYmoNCjw8L1R5cGUgL1BhZ2UvUGFyZW50IDMgMCBSL0NvbnRlbn
zIDUgMCBSL01lZGlhQm94IFswIDAgNjEyIDc5Ml0vUmVzb3VyY2VzPDwvRm9udDw8L0ZBQU) , not the pdf as it originally appeared, and the images do not open at all. The .md files seem to have exported as expected. 

I re-downloaded the enex file to ensure there were no corruption issues
I tried using it from usr/local/bin and ./evernote2md after extracting the program, but got the same result. 
Used default commands, as well as some flags and got the same result. 
Running kubuntu 22.04

Not sure what I'm doing wrong. 

Thanks for your help

**Comment by wormi4ok** [comment]
Thanks for reporting this issue, @michaelsmhc 
I guess the problem with Images is known (#66 sounds similar), I just can't get to fix it. But the issues with PDFs is something I'm not aware of. Would it be possible to upload a sample file, original and resulted pdf, to examine?

**Comment by michaelsmhc** [comment]
Hi @wormi4ok, and thanks for the quick reply. Here's an example of the original pdf, and the output from evernote2md:
[vitodens_100-b1ha_flyer (1).pdf](https://github.com/wormi4ok/evernote2md/files/10874981/vitodens_100-b1ha_flyer.1.pdf)
[vitodens_100-b1ha_flyer_(1).pdf](https://github.com/wormi4ok/evernote2md/files/10874982/vitodens_100-b1ha_flyer_.1.pdf)
[vitodens_100_B_flyer.md](https://github.com/wormi4ok/evernote2md/files/10874990/vitodens_100_B_flyer.md)

**Comment by wormi4ok** [comment]
Thanks! I see the problem with PDFs - they got exported in base64 encoded format. I think I've fixed it with the latest commit. Can you test it before I publish a new patch? You can build it locally from the latest master branch or use the binary attached.

[evernote2md_0.18.2_Linux_64-bit.tar.gz](https://github.com/wormi4ok/evernote2md/files/10889803/evernote2md_0.18.2_Linux_64-bit.tar.gz)

**Comment by michaelsmhc** [comment]
No problem. I tried it just now, and it worked flawlessly for both PDFs and images. Thank you!
